### ISSUE TITLE
Create proper landingpage

### ISSUE THREAD

**Issue by mstalfoort** [saffire/saffire#18]
For the few lines used to display http://www.saffire-lang.org/, you shouldn't have several validation errors. Please add the landingpage to GH so we can fix that for you.

**Comment by mstalfoort** [comment]
..perhaps its better to redirect it to the gh-pages in this repo so you have best of both worlds

**Comment by jaytaph** [comment]
Hi Marc, 

I know you like my frontend skills.. Admit it :-) (i wasn't allowed to use <blink> and <marquee> :| ) 

I've setup a http://saffire.github.com pages and repository: https://github.com/saffire/saffire.github.com.

If a decent page would exist, i would really appreciate this (and so does the rest of the internet)  Note though that we're busy with a decent page setup but that might take a while tough and you can checkout who's working on what on the IRC channel. 

If the github pages are done, I can switch the DNS to point to github pages.

**Comment by mstalfoort** [comment]
Hey,

indeed I was highly impressed by your skills ;)
For my understanding: you want the functionality from http://www.saffire-lang.org/ to be integrated in the newly created saffire GH page?

**Comment by jaytaph** [comment]
Yes, currently those are the only things we need. We're in the process of setting up and link to more stuff (documentation, userboards, wiki etc), but right now I'd like to focus on the language itself :-)

Also, if you need help on using blink, don't hesitate to DM me :-)

**Comment by jaytaph** [comment]
Marc, 

I'm closing this issue because a saffire github page has been created. You can add a PR there, and I will change the DNS afterwards. If needed, we can open an issue on that repository.
