### ISSUE TITLE
cmake install doen't seem to install the binary

### ISSUE THREAD

**Issue by jaytaph** [saffire/saffire#243]
cmake install doen't seem to install the binary. The CMake files do have `install` rule for the binary. But i cannot find any binaries in the `bin` directory (nor do i see anything in the verbose cmake)

**Comment by jaytaph** [comment]
@steazzalini I've looked at this issue, and found it.. The `build.sh` never triggers the `install` target, we only do a `make` inside this script.

Maybe it would be a nice thing to have a `./build.sh install` (or maybe a separate `./install.sh`?) that actually triggers `make install` from the correct directory?  (this should be a separate processed, as we can easily sudo this)

**Comment by ghost** [comment]
Ok, now I got it. Sorry for this false fix.
ASAIK the installation target is not defined by default by CMake.
I'll manage to define it asap :beer:

**Comment by jaytaph** [comment]
I think the fix is a nice addition, we will need to separate the libs/includes later on anyway :)

**Comment by jaytaph** [comment]
Fixed in #256
